# Generated by Django 3.1.7 on 2021-03-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210323_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
